import asyncio
from sqlmodel import SQLModel

from config.db import engine, async_session, close_db
from models import (
    admin_user,
    candidate_certification,
    candidate_language,
    candidate_payment,
    candidate_plan,
    candidate_software,
    candidate_study,
    candidate_suscription,
    candidate,
    certification_type,
    city,
    company_payment,
    company_plan,
    company_sector,
    company_suscription,
    company_user,
    company,
    contract_type,
    driver_license,
    generic_position,
    job_answer,
    job_day,
    job_offer,
    job_question,
    job_type,
    job_schedule,
    knownledge_level,
    language_level,
    language,
    password_reset,
    performance_area,
    postulation,
    publication_category,
    publication,
    region,
    role_position,
    shift,
    software,
    specific_position,
    alert_frequency,
    candidate_alert_configuration,
    candidate_position_preference,
    work_experience
)
from utilities import get_password_hash

async def initialize_db():
    try:
        # Create All Tables
        print("[INFO]: Creating All Tables")
        async with engine.begin() as conn:
            await conn.run_sync(SQLModel.metadata.create_all)
        # Insert Pre-Established Records
        async with async_session() as session:
            # Admin User Table
            admins = [
                admin_user.AdminUser(
                    name="Nombre Ejemplo",
                    paternal="Apellido Ejemplo",
                    email="admin@gmail.com",
                    password=get_password_hash("SecurePassword!")
                )
            ]
            # Region Table
            regions = [
                region.Region(name="Tarapacá"),
                region.Region(name="Antofagasta"),
                region.Region(name="Atacama"),
                region.Region(name="Coquimbo"),
                region.Region(name="Valparaíso"),
                region.Region(name="Lib. Gral. Bernardo O'Higgins"),
                region.Region(name="Maule"),
                region.Region(name="Biobío"),
                region.Region(name="La Araucanía"),
                region.Region(name="Los Lagos"),
                region.Region(name="Aysén del General Carlos Ibáñe"),
                region.Region(name="Magallanes y Antártica Chilena"),
                region.Region(name="Metropolitana de Santiago"),
                region.Region(name="Los Ríos"),
                region.Region(name="Arica y Parinacota"),
                region.Region(name="Ñuble")
            ]
            # City Table
            cities = [
                city.City(name="Arica", region_id=15),
                city.City(name="Camarones", region_id=15),
                city.City(name="Putre", region_id=15),
                city.City(name="General Lagos", region_id=15),
                city.City(name="Alto Hospicio", region_id=1),
                city.City(name="Iquique", region_id=1),
                city.City(name="Camiña", region_id=1),
                city.City(name="Colchane", region_id=1),
                city.City(name="Huara", region_id=1),
                city.City(name="Pica", region_id=1),
                city.City(name="Pozo Almonte", region_id=1),
                city.City(name="Antofagasta", region_id=2),
                city.City(name="Mejillones", region_id=2),
                city.City(name="Sierra Gorda", region_id=2),
                city.City(name="Taltal", region_id=2),
                city.City(name="Calama", region_id=2),
                city.City(name="Ollagüe", region_id=2),
                city.City(name="San Pedro de Atacama", region_id=2),
                city.City(name="María Elena", region_id=2),
                city.City(name="Tocopilla", region_id=2),
                city.City(name="Chañaral", region_id=3),
                city.City(name="Diego de Almagro", region_id=3),
                city.City(name="Caldera", region_id=3),
                city.City(name="Copiapó", region_id=3),
                city.City(name="Tierra Amarilla", region_id=3),
                city.City(name="Alto del Carmen", region_id=3),
                city.City(name="Freirina", region_id=3),
                city.City(name="Huasco", region_id=3),
                city.City(name="Vallenar", region_id=3),
                city.City(name="Canela", region_id=4),
                city.City(name="Illapel", region_id=4),
                city.City(name="Los Vilos", region_id=4),
                city.City(name="Salamanca", region_id=4),
                city.City(name="Andacollo", region_id=4),
                city.City(name="Coquimbo", region_id=4),
                city.City(name="La Higuera", region_id=4),
                city.City(name="La Serena", region_id=4),
                city.City(name="Paihuano", region_id=4),
                city.City(name="Vicuña", region_id=4),
                city.City(name="Combarbalá", region_id=4),
                city.City(name="Monte Patria", region_id=4),
                city.City(name="Ovalle", region_id=4),
                city.City(name="Punitaqui", region_id=4),
                city.City(name="Río Hurtado", region_id=4),
                city.City(name="Isla de Pascua", region_id=5),
                city.City(name="Calle Larga", region_id=5),
                city.City(name="Los Andes", region_id=5),
                city.City(name="Rinconada", region_id=5),
                city.City(name="San Esteban", region_id=5),
                city.City(name="La Ligua", region_id=5),
                city.City(name="Papudo", region_id=5),
                city.City(name="Petorca", region_id=5),
                city.City(name="Zapallar", region_id=5),
                city.City(name="Hijuelas", region_id=5),
                city.City(name="La Calera", region_id=5),
                city.City(name="La Cruz", region_id=5),
                city.City(name="Nogales", region_id=5),
                city.City(name="Quillota", region_id=5),
                city.City(name="Algarrobo", region_id=5),
                city.City(name="Cartagena", region_id=5),
                city.City(name="El Quisco", region_id=5),
                city.City(name="El Tabo", region_id=5),
                city.City(name="San Antonio", region_id=5),
                city.City(name="Santo Domingo", region_id=5),
                city.City(name="Catemu", region_id=5),
                city.City(name="Llaillay", region_id=5),
                city.City(name="Panquehue", region_id=5),
                city.City(name="Putaendo", region_id=5),
                city.City(name="San Felipe", region_id=5),
                city.City(name="Santa María", region_id=5),
                city.City(name="Casablanca", region_id=5),
                city.City(name="Concón", region_id=5),
                city.City(name="Juan Fernández", region_id=5),
                city.City(name="Puchuncaví", region_id=5),
                city.City(name="Quintero", region_id=5),
                city.City(name="Valparaíso", region_id=5),
                city.City(name="Viña del Mar", region_id=5),
                city.City(name="Limache", region_id=5),
                city.City(name="Olmué", region_id=5),
                city.City(name="Quilpué", region_id=5),
                city.City(name="Villa Alemana", region_id=5),
                city.City(name="Colina", region_id=13),
                city.City(name="Lampa", region_id=13),
                city.City(name="Tiltil", region_id=13),
                city.City(name="Pirque", region_id=13),
                city.City(name="Puente Alto", region_id=13),
                city.City(name="San José de Maipo", region_id=13),
                city.City(name="Buin", region_id=13),
                city.City(name="Calera de Tango", region_id=13),
                city.City(name="Paine", region_id=13),
                city.City(name="San Bernardo", region_id=13),
                city.City(name="Alhué", region_id=13),
                city.City(name="Curacaví", region_id=13),
                city.City(name="María Pinto", region_id=13),
                city.City(name="Melipilla", region_id=13),
                city.City(name="San Pedro", region_id=13),
                city.City(name="Cerrillos", region_id=13),
                city.City(name="Cerro Navia", region_id=13),
                city.City(name="Conchalí", region_id=13),
                city.City(name="El Bosque", region_id=13),
                city.City(name="Estación Central", region_id=13),
                city.City(name="Huechuraba", region_id=13),
                city.City(name="Independencia", region_id=13),
                city.City(name="La Cisterna", region_id=13),
                city.City(name="La Florida", region_id=13),
                city.City(name="La Granja", region_id=13),
                city.City(name="La Pintana", region_id=13),
                city.City(name="La Reina", region_id=13),
                city.City(name="Las Condes", region_id=13),
                city.City(name="Lo Barnechea", region_id=13),
                city.City(name="Lo Espejo", region_id=13),
                city.City(name="Lo Prado", region_id=13),
                city.City(name="Macul", region_id=13),
                city.City(name="Maipú", region_id=13),
                city.City(name="Ñuñoa", region_id=13),
                city.City(name="Pedro Aguirre Cerda", region_id=13),
                city.City(name="Peñalolén", region_id=13),
                city.City(name="Providencia", region_id=13),
                city.City(name="Pudahuel", region_id=13),
                city.City(name="Quilicura", region_id=13),
                city.City(name="Quinta Normal", region_id=13),
                city.City(name="Recoleta", region_id=13),
                city.City(name="Renca", region_id=13),
                city.City(name="San Miguel", region_id=13),
                city.City(name="San Joaquín", region_id=13),
                city.City(name="San Ramón", region_id=13),
                city.City(name="Santiago", region_id=13),
                city.City(name="Vitacura", region_id=13),
                city.City(name="El Monte", region_id=13),
                city.City(name="Isla de Maipo", region_id=13),
                city.City(name="Padre Hurtado", region_id=13),
                city.City(name="Peñaflor", region_id=13),
                city.City(name="Talagante", region_id=13),
                city.City(name="Codegua", region_id=6),
                city.City(name="Coinco", region_id=6),
                city.City(name="Coltauco", region_id=6),
                city.City(name="Doñihue", region_id=6),
                city.City(name="Graneros", region_id=6),
                city.City(name="Las Cabras", region_id=6),
                city.City(name="Machalí", region_id=6),
                city.City(name="Malloa", region_id=6),
                city.City(name="Mostazal", region_id=6),
                city.City(name="Olivar", region_id=6),
                city.City(name="Peumo", region_id=6),
                city.City(name="Pichidegua", region_id=6),
                city.City(name="Quinta de Tilcoco", region_id=6),
                city.City(name="Rancagua", region_id=6),
                city.City(name="Rengo", region_id=6),
                city.City(name="Requínoa", region_id=6),
                city.City(name="San Vicente", region_id=6),
                city.City(name="La Estrella", region_id=6),
                city.City(name="Litueche", region_id=6),
                city.City(name="Marchihue", region_id=6),
                city.City(name="Navidad", region_id=6),
                city.City(name="Paredones", region_id=6),
                city.City(name="Pichilemu", region_id=6),
                city.City(name="Chépica", region_id=6),
                city.City(name="Chimbarongo", region_id=6),
                city.City(name="Lolol", region_id=6),
                city.City(name="Nancagua", region_id=6),
                city.City(name="Palmilla", region_id=6),
                city.City(name="Peralillo", region_id=6),
                city.City(name="Placilla", region_id=6),
                city.City(name="Pumanque", region_id=6),
                city.City(name="San Fernando", region_id=6),
                city.City(name="Santa Cruz", region_id=6),
                city.City(name="Curicó", region_id=7),
                city.City(name="Hualañé", region_id=7),
                city.City(name="Licantén", region_id=7),
                city.City(name="Molina", region_id=7),
                city.City(name="Rauco", region_id=7),
                city.City(name="Romeral", region_id=7),
                city.City(name="Sagrada Familia", region_id=7),
                city.City(name="Teno", region_id=7),
                city.City(name="Vichuquén", region_id=7),
                city.City(name="Colbún", region_id=7),
                city.City(name="Linares", region_id=7),
                city.City(name="Longaví", region_id=7),
                city.City(name="Parral", region_id=7),
                city.City(name="Retiro", region_id=7),
                city.City(name="San Javier", region_id=7),
                city.City(name="Villa Alegre", region_id=7),
                city.City(name="Yerbas Buenas", region_id=7),
                city.City(name="Constitución", region_id=7),
                city.City(name="Curepto", region_id=7),
                city.City(name="Empedrado", region_id=7),
                city.City(name="Maule", region_id=7),
                city.City(name="Pelarco", region_id=7),
                city.City(name="Pencahue", region_id=7),
                city.City(name="Río Claro", region_id=7),
                city.City(name="San Clemente", region_id=7),
                city.City(name="San Rafael", region_id=7),
                city.City(name="Talca", region_id=7),
                city.City(name="Cauquenes", region_id=7),
                city.City(name="Chanco", region_id=7),
                city.City(name="Pelluhue", region_id=7),
                city.City(name="Cobquecura", region_id=16),
                city.City(name="Coelemu", region_id=16),
                city.City(name="Ninhue", region_id=16),
                city.City(name="Portezuelo", region_id=16),
                city.City(name="Quirihue", region_id=16),
                city.City(name="Ránquil", region_id=16),
                city.City(name="Treguaco", region_id=16),
                city.City(name="Bulnes", region_id=16),
                city.City(name="Chillán", region_id=16),
                city.City(name="Chillán Viejo", region_id=16),
                city.City(name="El Carmen", region_id=16),
                city.City(name="Pemuco", region_id=16),
                city.City(name="Pinto", region_id=16),
                city.City(name="Quillón", region_id=16),
                city.City(name="San Ignacio", region_id=16),
                city.City(name="Yungay", region_id=16),
                city.City(name="Coihueco", region_id=16),
                city.City(name="Ñiquén", region_id=16),
                city.City(name="San Carlos", region_id=16),
                city.City(name="San Fabián", region_id=16),
                city.City(name="San Nicolás", region_id=16),
                city.City(name="Arauco", region_id=8),
                city.City(name="Cañete", region_id=8),
                city.City(name="Contulmo", region_id=8),
                city.City(name="Curanilahue", region_id=8),
                city.City(name="Lebu", region_id=8),
                city.City(name="Los Álamos", region_id=8),
                city.City(name="Tirúa", region_id=8),
                city.City(name="Alto Biobío", region_id=8),
                city.City(name="Antuco", region_id=8),
                city.City(name="Cabrero", region_id=8),
                city.City(name="Laja", region_id=8),
                city.City(name="Los Ángeles", region_id=8),
                city.City(name="Mulchén", region_id=8),
                city.City(name="Nacimiento", region_id=8),
                city.City(name="Negrete", region_id=8),
                city.City(name="Quilaco", region_id=8),
                city.City(name="Quilleco", region_id=8),
                city.City(name="San Rosendo", region_id=8),
                city.City(name="Santa Bárbara", region_id=8),
                city.City(name="Tucapel", region_id=8),
                city.City(name="Yumbel", region_id=8),
                city.City(name="Chiguayante", region_id=8),
                city.City(name="Concepción", region_id=8),
                city.City(name="Coronel", region_id=8),
                city.City(name="Florida", region_id=8),
                city.City(name="Hualpén", region_id=8),
                city.City(name="Hualqui", region_id=8),
                city.City(name="Lota", region_id=8),
                city.City(name="Penco", region_id=8),
                city.City(name="San Pedro de la Paz", region_id=8),
                city.City(name="Santa Juana", region_id=8),
                city.City(name="Talcahuano", region_id=8),
                city.City(name="Tomé", region_id=8),
                city.City(name="Carahue", region_id=9),
                city.City(name="Cholchol", region_id=9),
                city.City(name="Cunco", region_id=9),
                city.City(name="Curarrehue", region_id=9),
                city.City(name="Freire", region_id=9),
                city.City(name="Galvarino", region_id=9),
                city.City(name="Gorbea", region_id=9),
                city.City(name="Lautaro", region_id=9),
                city.City(name="Loncoche", region_id=9),
                city.City(name="Melipeuco", region_id=9),
                city.City(name="Nueva Imperial", region_id=9),
                city.City(name="Padre Las Casas", region_id=9),
                city.City(name="Perquenco", region_id=9),
                city.City(name="Pitrufquén", region_id=9),
                city.City(name="Pucón", region_id=9),
                city.City(name="Saavedra", region_id=9),
                city.City(name="Temuco", region_id=9),
                city.City(name="Teodoro Schmidt", region_id=9),
                city.City(name="Toltén", region_id=9),
                city.City(name="Vilcún", region_id=9),
                city.City(name="Villarrica", region_id=9),
                city.City(name="Angol", region_id=9),
                city.City(name="Collipulli", region_id=9),
                city.City(name="Curacautín", region_id=9),
                city.City(name="Ercilla", region_id=9),
                city.City(name="Lonquimay", region_id=9),
                city.City(name="Los Sauces", region_id=9),
                city.City(name="Lumaco", region_id=9),
                city.City(name="Purén", region_id=9),
                city.City(name="Renaico", region_id=9),
                city.City(name="Traiguén", region_id=9),
                city.City(name="Victoria", region_id=9),
                city.City(name="Valdivia", region_id=14),
                city.City(name="Corral", region_id=14),
                city.City(name="Lanco", region_id=14),
                city.City(name="Los Lagos", region_id=14),
                city.City(name="Máfil", region_id=14),
                city.City(name="Mariquina", region_id=14),
                city.City(name="Paillaco", region_id=14),
                city.City(name="Panguipulli", region_id=14),
                city.City(name="La Unión", region_id=14),
                city.City(name="Futrono", region_id=14),
                city.City(name="Lago Ranco", region_id=14),
                city.City(name="Río Bueno", region_id=14),
                city.City(name="Ancud", region_id=10),
                city.City(name="Castro", region_id=10),
                city.City(name="Chonchi", region_id=10),
                city.City(name="Curaco de Vélez", region_id=10),
                city.City(name="Dalcahue", region_id=10),
                city.City(name="Puqueldón", region_id=10),
                city.City(name="Queilén", region_id=10),
                city.City(name="Quellón", region_id=10),
                city.City(name="Quemchi", region_id=10),
                city.City(name="Quinchao", region_id=10),
                city.City(name="Calbuco", region_id=10),
                city.City(name="Cochamó", region_id=10),
                city.City(name="Fresia", region_id=10),
                city.City(name="Frutillar", region_id=10),
                city.City(name="Llanquihue", region_id=10),
                city.City(name="Los Muermos", region_id=10),
                city.City(name="Maullín", region_id=10),
                city.City(name="Puerto Montt", region_id=10),
                city.City(name="Puerto Varas", region_id=10),
                city.City(name="Osorno", region_id=10),
                city.City(name="Puerto Octay", region_id=10),
                city.City(name="Purranque", region_id=10),
                city.City(name="Puyehue", region_id=10),
                city.City(name="Río Negro", region_id=10),
                city.City(name="San Juan de la Costa", region_id=10),
                city.City(name="San Pablo", region_id=10),
                city.City(name="Chaitén", region_id=10),
                city.City(name="Futaleufú", region_id=10),
                city.City(name="Hualaihué", region_id=10),
                city.City(name="Palena", region_id=10),
                city.City(name="Coyhaique", region_id=11),
                city.City(name="Lago Verde", region_id=11),
                city.City(name="Aysén", region_id=11),
                city.City(name="Cisnes", region_id=11),
                city.City(name="Guaitecas", region_id=11),
                city.City(name="Cochrane", region_id=11),
                city.City(name="O'Higgins", region_id=11),
                city.City(name="Tortel", region_id=11),
                city.City(name="Chile Chico", region_id=11),
                city.City(name="Río Ibáñez", region_id=11),
                city.City(name="Punta Arenas", region_id=12),
                city.City(name="Laguna Blanca", region_id=12),
                city.City(name="Río Verde", region_id=12),
                city.City(name="San Gregorio", region_id=12),
                city.City(name="Cabo de Hornos", region_id=12),
                city.City(name="Antártica", region_id=12),
                city.City(name="Porvenir", region_id=12),
                city.City(name="Primavera", region_id=12),
                city.City(name="Timaukel", region_id=12),
                city.City(name="Natales", region_id=12),
                city.City(name="Torres del Paine", region_id=12)
            ]
            # Area Performance Table
            areas = [
                performance_area.PerformanceArea(name="Asesoria y Legal"),
                performance_area.PerformanceArea(name="Atencion al cliente y Call Center"),
                performance_area.PerformanceArea(name="Comercial y Negocios"),
                performance_area.PerformanceArea(name="Contabilidad, Finanzas y Administración"),
                performance_area.PerformanceArea(name="Gerencia y Direccion General"),
                performance_area.PerformanceArea(name="Informatica y Comunicaciones"),
                performance_area.PerformanceArea(name="Ingenieria y Proyectos"),
                performance_area.PerformanceArea(name="Logistica y Abastecimiento"),
                performance_area.PerformanceArea(name="Marketing y Ventas"),
                performance_area.PerformanceArea(name="Produccion y Mantencion"),
                performance_area.PerformanceArea(name="Recursos Humanos y Relaciones Laborales"),
                performance_area.PerformanceArea(name="Servicios generales y Seguridad"),
                performance_area.PerformanceArea(name="Otras areas de desempeño")
            ]
            # Company Sector Table
            company_sectors = [
                company_sector.CompanySector(name="Asesoria"),
                company_sector.CompanySector(name="Agricola"),
                company_sector.CompanySector(name="Banca"),
                company_sector.CompanySector(name="Comercio"),
                company_sector.CompanySector(name="Comunicación"),
                company_sector.CompanySector(name="Construccion"),
                company_sector.CompanySector(name="Consultoria"),
                company_sector.CompanySector(name="Educacion"),
                company_sector.CompanySector(name="Energia"),
                company_sector.CompanySector(name="Entretenimiento"),
                company_sector.CompanySector(name="Forestal"),
                company_sector.CompanySector(name="Hoteleria"),
                company_sector.CompanySector(name="Ingenieria"),
                company_sector.CompanySector(name="Inmobiliaria"),
                company_sector.CompanySector(name="Maquinaria"),
                company_sector.CompanySector(name="Mineria"),
                company_sector.CompanySector(name="Naviera"),
                company_sector.CompanySector(name="Pesca"),
                company_sector.CompanySector(name="Retail"),
                company_sector.CompanySector(name="Salud"),
                company_sector.CompanySector(name="Tecnologia"),
                company_sector.CompanySector(name="Transporte"),
                company_sector.CompanySector(name="Otros sectores")
            ]
            # Publication Category Table
            categories = [
                publication_category.PublicationCategory(name="Noticia"),
                publication_category.PublicationCategory(name="Tips"),
                publication_category.PublicationCategory(name="Evento")
            ]
            # Contract Type Table
            contract_types = [
                contract_type.ContractType(name="Plazo Fijo"),
                contract_type.ContractType(name="Plazo Indefinido"),
                contract_type.ContractType(name="Por Obra o Faena"),
                contract_type.ContractType(name="Honorarios"),
                contract_type.ContractType(name="Freelance"),
                contract_type.ContractType(name="Practica"),
                contract_type.ContractType(name="Memorista"),
                contract_type.ContractType(name="Graduado"),
                contract_type.ContractType(name="Trainee")
            ]
            # Knownledge Level Table
            knownledge_levels = [
                knownledge_level.KnownledgeLevel(name="Básico"),
                knownledge_level.KnownledgeLevel(name="Intermedio"),
                knownledge_level.KnownledgeLevel(name="Avanzado"),
                knownledge_level.KnownledgeLevel(name="Experto")
            ]
            # Language Table
            languages = [
                language.Language(name="Español"),
                language.Language(name="Ingles"),
                language.Language(name="Francés"),
                language.Language(name="Alemán"),
                language.Language(name="Portugués"),
                language.Language(name="Italiano"),
                language.Language(name="Chino Mandarín"),
                language.Language(name="Japonés"),
                language.Language(name="Coreano"),
                language.Language(name="Ruso")
            ]
            # Language Level Table
            language_leves = [
                language_level.LanguageLevel(name="Básico"),
                language_level.LanguageLevel(name="Intermedio"),
                language_level.LanguageLevel(name="Avanzado"),
                language_level.LanguageLevel(name="Nativo"),
                language_level.LanguageLevel(name="Bilingüe")
            ]
            # Certification Type Table
            certification_types = [
                certification_type.CertificationType(name="Certificación Técnica"),
                certification_type.CertificationType(name="Certificación Profesional"),
                certification_type.CertificationType(name="Curso"),
                certification_type.CertificationType(name="Taller"),
                certification_type.CertificationType(name="Diplomado"),
                certification_type.CertificationType(name="Seminario"),
                certification_type.CertificationType(name="Webinar")
            ]
            # Driver License Table
            driver_licenses = [
                driver_license.DriverLicense(license="A1"),
                driver_license.DriverLicense(license="A2"),
                driver_license.DriverLicense(license="A3"),
                driver_license.DriverLicense(license="A4"),
                driver_license.DriverLicense(license="A5"),
                driver_license.DriverLicense(license="B"),
                driver_license.DriverLicense(license="C"),
                driver_license.DriverLicense(license="D"),
                driver_license.DriverLicense(license="E"),
                driver_license.DriverLicense(license="F"),
            ]
            # Role Position Table
            role_positions = [
                role_position.RolePosition(name="Tecnico"),
                role_position.RolePosition(name="Administrativo")
            ]
            # Generic Position Table
            generic_positions = [
                generic_position.GenericPosition(name="Soporte Informatico", role_id=1),
                generic_position.GenericPosition(name="Tecnico en Redes", role_id=1),
                generic_position.GenericPosition(name="Asistente Contable", role_id=2),
                generic_position.GenericPosition(name="Secretario Ejecutivo", role_id=2)
            ]
            # Alert Frequency Table
            alert_frequencies = [
                alert_frequency.AlertFrequency(name="Semanal", days=7, description="Cada 7 dias"),
                alert_frequency.AlertFrequency(name="Quincenal", days=15, description="Cada 15 dias"),
                alert_frequency.AlertFrequency(name="Mensual", days=30, description="Cada 30 dias"),
            ]
            # Commit Transaction
            all_tables = (
                admins +
                regions +
                cities +
                areas +
                company_sectors +
                categories +
                contract_types +
                knownledge_levels +
                languages +
                language_leves +
                certification_types +
                driver_licenses +
                role_positions +
                generic_positions +
                alert_frequencies
            )
            session.add_all(all_tables)
            await session.commit()
        # Close DB Connection
        await close_db()
        print("[INFO]: Successful initialization of the database")
    except Exception as error:
        print(f"[ERROR]: Error initializing database: {error}")

asyncio.run(initialize_db())